server:
  port: 9090

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  expiration: 300000 # 5 minutes
spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver